[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
# dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
# dependencies = ["clean"]

[tasks.example]
command = "cargo"
args = ["run","--example"]
# dependencies = ["clean","format"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]
